#!/bin/bash
create-backbone-usage() {
cat <<"USAGE"
Usage:project [OPTIONS] <name>
	-h, --help        		show this help screen
	install     	  		install NPM PACKAGES
	uninstall    	  		uninstall NPM PACKAGES
	vhost (create,delete)   vhost builde
	grunt (command) 		grunt command
	server 				    start expressjs serve

Examples:
	project foo
	project foo action

USAGE
exit 0
}

backbone-install() {
	cd web/config
	echo '*************************************'
	echo '*  INSTALLING BACKBONE NPM PACKAGES *'
	echo '*************************************'
	npm install grunt
	npm install
	cd ../..
	echo '*************************************'
	echo '*               DONE                *'
	echo '*************************************'
	exit 0
}

backbone-server() {
	directory=$(basename "$PWD")
	path='/home/marcel/workspace/'$directory
	vagrant ssh -c "cd $path; sudo server $cmd"
}

backbone-setup() {
	name=$(basename "$PWD")
	source ~/.bashrc
	echo $VNNMPATH
	sudo sed -e '/'$name'.dev/d' -i '' /private/etc/hosts 
	sudo -- sh -c "echo '192.168.68.12 '$name.dev >> /private/etc/hosts"

	cp web/config/server.json.default web/config/server.json
	sed -i -e 's/\$BASEURL/'$name'.dev/g'  web/config/server.json
	ln -s $VNNMPATH'/Vagrantfile' Vagrantfile
	ln -s $VNNMPATH'/.vagrant' .vagrant
	backbone server install
	backbone server init
	backbone server start

}


backbone-grunt() {
	echo "grunt-command executing"
	cd web/config
	grunt $cmd
	cd ../..
	exit 0
}


# Loop to read -e options and arguments.
while [ $1 ]; do
	case "$1" in
		'--help'|'-h')
			create-backbone-usage;;
		'grunt')
			cmd="$2"
			backbone-grunt;;
		'server')
			cmd="$2"
			backbone-server;;
		'setup')
			backbone-setup;;

		'install')
			backbone-install;;
	esac
	shift
done

exit 0
